#!/usr/bin/env ruby
hostname = ARGV[0]
abort "Missing argument: cname of the account to export." if hostname.nil?

require 'json'
require 'pathname'

require_relative "../lib/scrollytelling/export/account"

account = Scrollytelling::Export::Account.new hostname
index = JSON.parse(account.index.read)
index['entries'].each do |entry|
  puts entry['canonical_url']
end
