#!/usr/bin/env ruby
hostname = ARGV[0]
abort "Missing argument: cname of the account to export." if hostname.nil?

require 'json'
require 'pathname'
require 'active_support'
require 'active_support/core_ext/object/blank'

require_relative "../lib/scrollytelling/export/account"

account = Scrollytelling::Export::Account.new hostname
account.create_root_dirs!

# The purpose of this file is to print all paths to the media bucket.
# One path per line.
# The calling script can then sync the bucket to the local environment.
#
# media bucket paths:
# /audio_files.url
# /image_files.url
# /video_files.url
# /video_files.poster
#
# output bucket paths:
# /audio_files./sources.url
# /video_files./sources.url

index = JSON.parse(account.index.read)
index['entries'].each do |entry|
  %w[audio_files image_files video_files].each do |type|
    entry[type].each do |file|
      next unless file.present?
      puts file['path']
        .split('/')[0,7]
        .join('/')
    end
  end
end
