#!/usr/bin/env ruby
require 'json'
require 'pathname'
require 'active_support'
require 'active_support/core_ext/object/blank'

require_relative "../lib/scrollytelling/export/account"

hostname = ENV.fetch('ACCOUNT')

account = Scrollytelling::Export::Account.new hostname
index = JSON.parse(account.index.read)
index['entries'].each do |entry|
  %w[audio_files image_files video_files].each do |type|
    entry[type].each do |file|
      next if file.nil?

      url = file['url']
      if url.present?
        puts url
          .sub(/\?\d*\z/, '')
          .sub(/\Ahttps:\/\//, '')
          .sub('.io', '.com')
          .sub('.s3-website.eu-central-1.amazonaws.com/radion', '/main')
          .sub(/\/original.*\z/, '')
          .sub(/\/v1.*\z/, '')
      end

      poster = file['poster']
      if poster.present?
        puts poster
          .sub(/\?\d*\z/, '')
          .sub(/\Ahttps:\/\//, '')
          .sub('.io', '.com')
          .sub('.s3-website.eu-central-1.amazonaws.com/radion', '/main')
          .sub(/\/original.*\z/, '')
          .sub(/\/v1.*\z/, '')
      end
    end
  end
end
