#!/usr/bin/env ruby
hostname = ARGV[0]
abort "Missing argument: cname of the account to export." if hostname.nil?

require 'json'
require 'pathname'
require 'active_support'
require 'active_support/core_ext/object/blank'

require_relative "../lib/scrollytelling/export/account"

account = Scrollytelling::Export::Account.new hostname
account.create_root_dirs!

index = JSON.parse(account.index.read)
index['entries'].each do |entry|
  %w[audio_files image_files video_files].each do |type|
    entry[type].each do |file|
      next unless file['sources']

      file['sources'].each do |source|
        puts account.clean(source['url'])
      end
    end
  end
end
