#!/usr/bin/env ruby
hostname = ARGV[0]
abort "Missing argument: cname of the account to export." if hostname.nil?

require 'json'
require 'pathname'
require 'active_support'
require 'active_support/core_ext/object/blank'

require_relative "../lib/scrollytelling/export/account"

account = Scrollytelling::Export::Account.new hostname
account.create_root_dirs!

index = JSON.parse(account.index.read)
index['entries'].each do |entry|
  %w[audio_files image_files video_files].each do |type|
    files = entry[type]
    next if files.nil?

    files.each do |file|
      sources = file['sources']
      next if sources.nil?

      sources.each do |source|
        puts source['path']
          .sub('radion', 'main')
          .split('/')[2,8]
          .join('/') if file.present?
      end
    end
  end
end
