#!/usr/bin/env ruby

require 'active_support'
require 'active_support/core_ext/object/blank'

require_relative "../lib/scrollytelling/export/export"
require_relative "../lib/scrollytelling/export/account"

require 'fileutils'

filename = ARGV[0]
backup = filename.sub(/html\z/, 'orig.html')

FileUtils.copy_file(filename, backup) unless File.exists?(backup)

slug = filename.split('/')[1]

index = File.readlines filename
tidied = index
  .reject {|l| l.blank? }
  .reject {|l| l.include? 'csrf' }
  .reject {|l| l.include? 'data-name="entry"' }
  .insert(3, '    <meta charset="utf-8">')
  .insert(18, %Q[    <link rel="stylesheet" media="all" href="/scrollytelling.link/entries/#{slug}.css" data-name="entry" />])

tidied.slice!(5..7) if tidied[5].include? "<script>"
File.open(filename, 'wt') {|f| f.puts tidied }
