#!/usr/bin/env ruby

hostname = ARGV[0]
abort "Missing argument: cname of the account to export." if hostname.nil?

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)

Webdrivers.cache_time = 86_400

require 'json'
require_relative '../lib/scrollytelling/export/account'
require_relative '../lib/scrollytelling/export/screenshot'
require_relative '../lib/scrollytelling/export/story'

$account = Scrollytelling::Export::Account.new hostname

index = JSON.parse($account.index.read)

index['entries'].each do |entry|
  story = Scrollytelling::Export::Story.new(entry)
  screenshot = Scrollytelling::Export::Screenshot.new story
  screenshot.create_all!
  entry['screenshots'] = screenshot.paths
  $account.index.write(JSON.pretty_generate(index), mode: 'wt')

  system("exiftool -overwrite_original -Title=\"#{story.title}\" -Language=#{entry['locale']} -Category=screenshot -ImageDescription=\"Large screenshot of the online story «#{story.title}». It was made using a scripted Chrome browser in the process of archiving the full story.\" -CreateDate=\"#{Time.now.to_s[0,19]}\" -OwnerName=Scrollytelling -Copyright='CC-BY-4.0' -XMP:source=\"#{story.url}\" -XMP:relation=\"https://www.scrollytelling.com\" #{story.screenshots}")

end
